(function(g){var window=this;var UAa=function(a,b){return g.Rb(a,b)},Q6=function(a){g.Cm(a,"zx",g.vb());
return a},R6=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.Fm(a.g,b,c)},VAa=function(a,b){var c=[];
g.rk(b,function(a){try{var b=g.aD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.$C(b)&&c.push(a):c.push(a)},a);
return c},WAa=function(a,b){var c=VAa(a,b);
(0,g.C)(c,function(a){g.aD.prototype.remove.call(this,a)},a)},XAa=function(a){if(a.Bd){if(a.Bd.locationOverrideToken)return{locationOverrideToken:a.Bd.locationOverrideToken};
if(null!=a.Bd.latitudeE7&&null!=a.Bd.longitudeE7)return{latitudeE7:a.Bd.latitudeE7,longitudeE7:a.Bd.longitudeE7}}return null},YAa=function(a,b,c,d){var e=new g.tm(null,void 0);
a&&g.um(e,a);b&&g.vm(e,b);c&&g.wm(e,c);d&&g.xm(e,d);return e},ZAa=function(a){g.QF[a]&&(a=g.QF[a],(0,g.C)(a,function(a){g.OF[a]&&delete g.OF[a]}),a.length=0)},$Aa=function(a){var b=g.NF();
if(b)if(b.clear(a),a)ZAa(a);else for(var c in g.QF)ZAa(c)},S6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.nm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",aBa(this,a.capabilities||""),bBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},aBa=function(a,b){a.capabilities.clear();
(0,g.Id)(b.split(","),g.Ea(UAa,cBa)).forEach(function(b){a.capabilities.add(b)})},bBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},T6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},U6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},dBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},eBa=function(a){return new T6(a)},fBa=function(a){return g.ya(a)?(0,g.I)(a,eBa):[]},V6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},W6=function(a){return g.ya(a)?"["+(0,g.I)(a,V6).join(",")+"]":"null"},X6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},gBa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},Y6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},Z6=function(a,b){return g.Ja(a,function(a){return U6(a,b)})},hBa=function(){var a=(0,g.JG)();
a&&WAa(a,a.g.Rd(!0))},$6=function(){var a=g.MG("yt-remote-connected-devices")||[];
g.eb(a);return a},iBa=function(a){if(g.Oa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},jBa=function(a){g.LG("yt-remote-connected-devices",a,86400)},b7=function(){if(a7)return a7;
var a=g.MG("yt-remote-device-id");a||(a=X6(),g.LG("yt-remote-device-id",a,31536E3));for(var b=$6(),c=1,d=a;g.Na(b,d);)c++,d=a+"#"+c;return a7=d},c7=function(){var a=$6(),b=b7();
g.Na(a,b);g.OG()&&g.gb(a,b);a=iBa(a);if(g.Oa(a))try{g.wG("remote_sid")}catch(c){}else try{g.vG("remote_sid",a.join(","),-1)}catch(c){}},kBa=function(){return g.MG("yt-remote-session-browser-channel")},lBa=function(){return g.MG("yt-remote-local-screens")||[]},mBa=function(){g.LG("yt-remote-lounge-token-expiration",!0,86400)},nBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(lBa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.bm)(c,function(a){return!g.Na(b,a)})&&mBa();
g.LG("yt-remote-local-screens",a,31536E3)},oBa=function(a,b){g.LG("yt-remote-session-browser-channel",a);
g.LG("yt-remote-session-screen-id",b);var c=$6(),d=b7();g.Na(c,d)||c.push(d);jBa(c);c7()},d7=function(a){a||(g.NG("yt-remote-session-screen-id"),g.NG("yt-remote-session-video-id"));
c7();a=$6();g.Sa(a,b7());jBa(a)},pBa=function(){if(!e7){var a=g.lD();
a&&(e7=new g.VC(a))}return e7?!!e7.get("yt-remote-use-staging-server"):!1},qBa=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.zb(a)},rBa=function(a,b){var c=g.Bd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Yc(c,g.$d("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},sBa=function(){var a=qBa(),b=window.document.getElementById(a),c=b&&g.ZE(b,"loaded");
c||b&&!c||(b=rBa(a,function(){g.ZE(b,"loaded")||(g.YE(b,"loaded","true"),g.UF(a),g.UD(g.Ea($Aa,a),0))}))},f7=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},tBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},g7=function(a){a.length?uBa(a.shift(),function(){g7(a)}):h7()},vBa=function(a){return"chrome-extension://"+a+i7},uBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},j7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},h7=function(){var a=tBa();
a&&a(!1,"No cast extension found")},k7=function(){if(wBa){var a=2,b=tBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;uBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",h7,c)}},xBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(k7(),a({command:"cast.sender.init"}))},yBa=function(){k7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);g7(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+i7,"//www.gstatic.com/eureka/clank"+i7])},l7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.rd=b;this.B=(0,g.A)(this.tJ,this);this.g=!1;this.l=0;this.o=this.Ba=null;this.A=[]},m7=function(){},n7=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Jm(this);this.l=new g.pg;this.l.setInterval(250)},ABa=function(a,b,c){a.Kj=1;
a.jh=Q6(b.clone());a.Oi=c;a.B=!0;zBa(a,null)},o7=function(a,b,c,d,e){a.Kj=1;
a.jh=Q6(b.clone());a.Oi=null;a.B=c;e&&(a.PD=!1);zBa(a,d)},zBa=function(a,b){a.xk=(0,g.G)();
p7(a);a.Hh=a.jh.clone();R6(a.Hh,"t",a.C);a.Km=0;a.Sc=a.g.Kr(a.g.Bm()?b:null);0<a.xs&&(a.Gp=new g.Uk((0,g.A)(a.dF,a,a.Sc),a.xs));a.W.U(a.Sc,"readystatechange",a.LU);var c=a.mi?g.Zb(a.mi):{};a.Oi?(a.rq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Sc.send(a.Hh,a.rq,a.Oi,c)):(a.rq="GET",a.PD&&!g.xd&&(c.Connection="close"),a.Sc.send(a.Hh,a.rq,null,c));a.g.xf(1)},DBa=function(a,b,c){for(var d=!0;!a.Wh&&a.Km<c.length;){var e=BBa(a,c);
if(e==q7){4==b&&(a.kh=4,r7(15),d=!1);break}else if(e==CBa){a.kh=4;r7(16);d=!1;break}else s7(a,e)}4==b&&0==c.length&&(a.kh=1,r7(17),d=!1);a.Df=a.Df&&d;d||(t7(a),u7(a))},BBa=function(a,b){var c=a.Km,d=b.indexOf("\n",c);
if(-1==d)return q7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return CBa;d+=1;if(d+c>b.length)return q7;var e=b.substr(d,c);a.Km=d+c;return e},FBa=function(a,b){a.xk=(0,g.G)();
p7(a);var c=b?window.location.hostname:"";a.Hh=a.jh.clone();g.Cm(a.Hh,"DOMAIN",c);g.Cm(a.Hh,"t",a.C);try{a.Ef=new window.ActiveXObject("htmlfile")}catch(n){t7(a);a.kh=7;r7(22);u7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in v7)k=v7[l];else if(l in EBa)k=v7[l]=EBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=v7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Zc(g.uc("b/12014412"),d);a.Ef.open();a.Ef.write(g.Qc(c));a.Ef.close();a.Ef.parentWindow.m=(0,g.A)(a.ST,a);a.Ef.parentWindow.d=(0,g.A)(a.bD,a,!0);a.Ef.parentWindow.rpcClose=(0,g.A)(a.bD,a,!1);c=a.Ef.createElement("DIV");a.Ef.parentWindow.document.body.appendChild(c);d=g.Hc(a.Hh.toString());d=g.ob(g.Ec(d));d=g.Zc(g.uc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Qc(d);
a.g.xf(1)},p7=function(a){a.Zv=(0,g.G)()+a.A;
GBa(a,a.A)},GBa=function(a,b){if(null!=a.Ok)throw Error("WatchDog timer not null");
a.Ok=w7((0,g.A)(a.kU,a),b)},x7=function(a){a.Ok&&(g.x.clearTimeout(a.Ok),a.Ok=null)},u7=function(a){a.g.nz()||a.Wh||a.g.tp(a)},t7=function(a){x7(a);
g.Ye(a.Gp);a.Gp=null;a.l.stop();g.Pm(a.W);if(a.Sc){var b=a.Sc;a.Sc=null;b.abort();b.dispose()}a.Ef&&(a.Ef=null)},s7=function(a,b){try{a.g.UC(a,b),a.g.xf(4)}catch(c){}},IBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;HBa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){IBa(a,b,c,d,f)},f)})}},HBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{y7(d),c(!0)}catch(e){}};
d.onerror=function(){try{y7(d),c(!1)}catch(e){}};
d.onabort=function(){try{y7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{y7(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},y7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},JBa=function(a){this.g=a;
this.l=new m7},KBa=function(a){var b=z7(a.g,a.Vk,"/mail/images/cleardot.gif");
Q6(b);IBa(b.toString(),5E3,(0,g.A)(a.DI,a),3,2E3);a.xf(1)},B7=function(a){var b=a.g.H;
if(null!=b)r7(5),b?(r7(11),A7(a.g,a,!1)):(r7(12),A7(a.g,a,!0));else if(a.se=new n7(a,void 0,void 0,void 0),a.se.mi=a.us,b=a.g,b=z7(b,b.Bm()?a.yl:null,a.ws),r7(5),!g.vd||g.oc(10))R6(b,"TYPE","xmlhttp"),o7(a.se,b,!1,a.yl,!1);else{R6(b,"TYPE","html");var c=a.se;a=!!a.yl;c.Kj=3;c.jh=Q6(b.clone());FBa(c,a)}},C7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new m7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},LBa=function(a,b){this.g=a;
this.map=b;this.context=null},MBa=function(a){g.$e.call(this,"statevent",a)},NBa=function(a,b){g.$e.call(this,"timingevent",a);
this.size=b},OBa=function(a){g.$e.call(this,"serverreachability",a)},RBa=function(a){PBa(a);
if(3==a.g){var b=a.gm++,c=a.ao.clone();g.Cm(c,"SID",a.o);g.Cm(c,"RID",b);g.Cm(c,"TYPE","terminate");D7(a,c);b=new n7(a,a.o,b,void 0);b.Kj=2;b.jh=Q6(c.clone());(new window.Image).src=b.jh;b.xk=(0,g.G)();p7(b)}QBa(a)},SBa=function(a){a.bJ(1,0);
a.ao=z7(a,null,a.ts);E7(a)},PBa=function(a){a.ah&&(a.ah.abort(),a.ah=null);
a.xc&&(a.xc.cancel(),a.xc=null);a.rg&&(g.x.clearTimeout(a.rg),a.rg=null);F7(a);a.Xd&&(a.Xd.cancel(),a.Xd=null);a.eh&&(g.x.clearTimeout(a.eh),a.eh=null)},TBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new LBa(a.IP++,b));2!=a.g&&3!=a.g||E7(a)},E7=function(a){a.Xd||a.eh||(a.eh=w7((0,g.A)(a.ZC,a),0),a.vj=0)},VBa=function(a,b){if(1==a.g){if(!b){a.gm=Math.floor(1E5*Math.random());
var c=a.gm++,d=new n7(a,"",c,void 0);d.mi=null;var e=G7(a),f=a.ao.clone();g.Cm(f,"RID",c);g.Cm(f,"CVER","1");D7(a,f);ABa(d,f,e);a.Xd=d;a.g=2}}else 3==a.g&&(b?UBa(a,b):0==a.l.length||a.Xd||UBa(a))},UBa=function(a,b){if(b)if(6<a.Yh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.gm-1;var d=G7(a)}else c=b.D,d=b.Oi;else c=a.gm++,d=G7(a);var e=a.ao.clone();g.Cm(e,"SID",a.o);g.Cm(e,"RID",c);g.Cm(e,"AID",a.Yj);D7(a,e);c=new n7(a,a.o,c,a.vj+1);c.mi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Xd=c;ABa(c,e,d)},D7=function(a,b){if(a.qd){var c=a.qd.Uy();
c&&g.Hb(c,function(a,c){g.Cm(b,c,a)})}},G7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Yh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Yh?e:f-d;try{g.Hb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},WBa=function(a){a.xc||a.rg||(a.D=1,a.rg=w7((0,g.A)(a.YC,a),0),a.hj=0)},H7=function(a){if(a.xc||a.rg||3<=a.hj)return!1;
a.D++;a.rg=w7((0,g.A)(a.YC,a),XBa(a,a.hj));a.hj++;return!0},A7=function(a,b,c){a.qq=c;
a.Pf=b.Cg;a.C||SBa(a)},F7=function(a){null!=a.bi&&(g.x.clearTimeout(a.bi),a.bi=null)},XBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},I7=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.A)(a.EV,a);c||(c=new g.tm("//www.google.com/images/cleardot.gif"),Q6(c));HBa(c.toString(),1E4,d)}else r7(2);YBa(a,b)},YBa=function(a,b){a.g=0;
a.qd&&a.qd.Px(b);QBa(a);PBa(a)},QBa=function(a){a.g=0;
a.Pf=-1;if(a.qd)if(0==a.A.length&&0==a.l.length)a.qd.xr();else{g.Va(a.A);var b=g.Va(a.l);a.A.length=0;a.l.length=0;a.qd.xr(b)}},z7=function(a,b,c){var d=g.Dm(c);
if(""!=d.l)b&&g.vm(d,b+"."+d.l),g.wm(d,d.B);else{var e=window.location;d=YAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.kl&&g.Hb(a.kl,function(a,b){g.Cm(d,b,a)});
g.Cm(d,"VER",a.Yh);D7(a,d);return d},w7=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},r7=function(a){J7.dispatchEvent(new MBa(J7,a))},ZBa=function(){},$Ba=function(a,b){this.action=a;
this.params=b||{}},K7=function(a,b){g.M.call(this);
this.g=new g.Vt(this.IT,0,this);g.N(this,this.g);this.rd=5E3;this.l=0;if(g.Aa(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},L7=function(a,b,c){this.J=a;
this.C=b;this.o=new g.UC;this.l=new K7(this.kW,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.K=c||!1},aCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.qq,sessionId:a.g.o,arrayId:a.g.Yj}},bCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&VBa(a.g),RBa(a.g));a.F=0},M7=function(a){return!!a.g&&3==a.g.g},cCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},N7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Fg(a)||"";b&&(this.port=":"+b);this.domain=g.Eg(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yb(a,"10.0")&&(this.l=!1))},O7=function(a,b){var c=a.g;
if(g.u(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Og(c+b,{})},P7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),yd:g.Ea(a.B,e)};c&&(a.Nb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.kE(b,a)},gCa=function(){var a=dCa;
eCa();Q7.push(a);fCa(Q7)},R7=function(a,b){eCa();
var c=Q7,d=hCa(a,String(b));g.Oa(c)?iCa(d):(fCa(c),(0,g.C)(c,function(a){a(d)}))},eCa=function(){Q7||(Q7=g.y("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",Q7,void 0))},iCa=function(a){var b=(S7+1)%50;
S7=b;T7[b]=a;U7||(U7=49==b)},fCa=function(a){var b=T7;
if(b[0]){var c=S7,d=U7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
T7=Array(50);S7=-1;U7=!1}},hCa=function(a,b){var c=((0,g.G)()-jCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},V7=function(a){g.FF.call(this);
this.D=a;this.g=[]},kCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},lCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Id)(a.g,function(a){return!!Y6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=kCa(a,b[d])||c;return c},mCa=function(a,b){var c=a.g.length;
a.g=(0,g.Id)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},W7=function(a,b,c,d){g.FF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ba=window.NaN},Y7=function(a){V7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;X7(this);this.info("Initializing with "+W6(this.g))},nCa=function(a){if(a.g.length){var b=(0,g.I)(a.g,function(a){return a.id}),c=O7(a.o,"/pairing/get_lounge_token_batch");
P7(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.GJ,a),(0,g.A)(a.FJ,a))}},X7=function(a){var b=fBa(lBa());
b=(0,g.Id)(b,function(a){return!a.uuid});
return lCa(a,b)},Z7=function(a,b){nBa((0,g.I)(a.g,dBa));
b&&mBa()},a8=function(a,b){g.FF.call(this);
this.C=b;var c=g.MG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Na(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;$7("Initialized with "+g.wg(this.g))},oCa=function(a,b,c){var d=O7(a.B,"/pairing/get_screen_availability");
P7(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},b8=function(a,b){a:if(g.Lb(b)!=g.Lb(a.g))var c=!1;
else{c=g.Ob(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||($7("Updated online screens: "+g.wg(a.g)),a.g=b,a.T("screenChange"));pCa(a)},c8=function(a){(0,window.isNaN)(a.o)||g.WD(a.o);
a.o=g.UD((0,g.A)(a.ov,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},$7=function(a){R7("OnlineScreenService",a)},qCa=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.hc("Requesting availability of screen w/o lounge token.")});
return b},pCa=function(a){a=g.Ob(g.Ib(a.g,function(a){return a}));
g.eb(a);a.length?g.LG("yt-remote-online-screen-ids",a.join(","),60):g.NG("yt-remote-online-screen-ids")},d8=function(a){V7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};rCa(this)},tCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ke();if(k=(c?Z6(k,c):null)||Z6(k,b)){k.uuid=b;var l=e8(a,k);oCa(a.l,l,function(a){e(a?l:null)})}else c?sCa(a,c,(0,g.A)(function(a){var f=e8(this,new T6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));oCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},uCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},sCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Nb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.kE(O7(a.C,"/pairing/get_lounge_token_batch"),e)},vCa=function(a){a.g=a.o.ke();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+W6(a.g))},rCa=function(a){f8(a);
a.o=new Y7(a.C);a.o.subscribe("screenChange",(0,g.A)(a.VJ,a));vCa(a);a.A=fBa(g.MG("yt-remote-automatic-screen-cache")||[]);f8(a);a.info("Initializing automatic screens: "+W6(a.A));a.l=new a8(a.C,(0,g.A)(a.ke,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.T("onlineScreenChange")},a))},e8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Z6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.LG("yt-remote-automatic-screen-cache",(0,g.I)(a.A,dBa)));f8(a);a.B[b.uuid]=b.id;g.LG("yt-remote-device-id-map",a.B,31536E3);return b},f8=function(a){a.B=g.MG("yt-remote-device-id-map")||{}},g8=function(a,b,c){g.FF.call(this);
this.K=c;this.H=a;this.l=b;this.o=null},h8=function(a,b){R7(a.K,b)},i8=function(a,b){g8.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.qW,this);this.B=(0,g.A)(this.wU,this);this.A=g.UD((0,g.A)(function(){wCa(this,null)},this),12E4)},xCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.wg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){h8(this,"Failed to send message: getMdxSessionStatus.")},a)):h8(a,"Sending yt message without session: "+g.wg(b))},wCa=function(a,b){g.WD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.up,a),d=(0,g.A)(a.re,a);a.fz(b,c,d,5)}}else a.re(Error("Waiting for session status timed out."))},j8=function(a,b,c){g8.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.z;this.C=window.NaN;this.J=(0,g.A)(this.tW,this);this.g=g.z},yCa=function(a){a.g=a.H.kF(a.I,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.z;
this.up(a)},a),(0,g.A)(function(a){this.g=g.z;
this.re(a)},a))},zCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}pBa()&&(b.env_useStageMdx=1);return g.Mg(b)},k8=function(a,b){g8.call(this,a,b,"ManualSession");
this.g=g.UD((0,g.A)(this.ak,this,null),150)},l8=function(a,b,c,d){g.FF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.VS,this)},ACa=function(a,b){return b?g.Ja(a.o,function(a){return U6(b,a.label)},a):null},m8=function(a){R7("Controller",a)},dCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},n8=function(a){return a.B||!!a.o.length||!!a.g},o8=function(a,b,c){b!=a.g&&(g.Ye(a.g),(a.g=b)?(c?a.T("yt-remote-cast2-receiver-resumed",b.l):a.T("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.WC,a,b)),b.o?a.T("yt-remote-cast2-session-change",b.o):c&&a.g.ak(null)):a.T("yt-remote-cast2-session-change",null))},BCa=function(a){var b=a.l.jF(),c=a.g&&a.g.l;
a=(0,g.I)(b,function(a){c&&U6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=ACa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},HCa=function(a,b,c,d,e,f,k){CCa()?DCa(b,e,f,k)&&(q8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?ECa(a,c):(window.__onGCastApiAvailable=function(b,d){b?ECa(a,c):(r8("Failed to load cast API: "+d),s8(!1),q8(!1),g.NG("yt-remote-cast-available"),g.NG("yt-remote-cast-receiver"),FCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):sBa():j7("CriOS")?xBa():j7("Android")&&j7("Chrome/")&&window.navigator.presentation?yBa():window.chrome&&window.navigator.presentation&&!j7("Edge")?(k7(),g7(GCa.map(vBa))):h7())):p8("Cannot initialize because not running Chrome")},FCa=function(){p8("dispose");
var a=t8();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);ICa(!1);g.SF(u8);u8.length=0},v8=function(){return!!g.MG("yt-remote-cast-installed")},JCa=function(){var a=g.MG("yt-remote-cast-receiver");
return a?a.friendlyName:null},KCa=function(){p8("clearCurrentReceiver");
g.NG("yt-remote-cast-receiver")},LCa=function(){return v8()?t8()?t8().getCastSession():(r8("getCastSelector: Cast is not initialized."),null):(r8("getCastSelector: Cast API is not installed!"),null)},x8=function(){v8()?t8()?w8()?(p8("Requesting cast selector."),t8().requestSession()):(p8("Wait for cast API to be ready to request the session."),u8.push(g.RF("yt-remote-cast2-api-ready",x8))):r8("requestCastSelector: Cast is not initialized."):r8("requestCastSelector: Cast API is not installed!")},y8=
function(a,b){w8()?t8().setConnectedScreenStatus(a,b):r8("setConnectedScreenStatus called before ready.")},CCa=function(){var a=0<=g.Fb.search(/ (CrMo|Chrome|CriOS)\//);
return g.xI||a},MCa=function(a,b){t8().init(a,b)},DCa=function(a,b,c,d){var e=!1;
t8()||(a=new l8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.LG("yt-remote-cast-available",a);g.VF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){p8("onReceiverSelected: "+a.friendlyName);
g.LG("yt-remote-cast-receiver",a);g.VF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){p8("onReceiverResumed: "+a.friendlyName);
g.LG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){p8("onSessionChange: "+V6(a));
a||g.NG("yt-remote-cast-receiver");g.VF("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
p8("cloudview.createSingleton_: "+e);return e},t8=function(){return g.y("yt.mdx.remote.cloudview.instance_")},ECa=function(a,b){s8(!0);
q8(!1);MCa(a,function(a){a?(ICa(!0),g.UF("yt-remote-cast2-api-ready")):(r8("Failed to initialize cast API."),s8(!1),g.NG("yt-remote-cast-available"),g.NG("yt-remote-cast-receiver"),FCa());b(a)})},p8=function(a){R7("cloudview",a)},r8=function(a){R7("cloudview",a)},s8=function(a){p8("setCastInstalled_ "+a);
g.LG("yt-remote-cast-installed",a)},w8=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},ICa=function(a){p8("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},q8=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},z8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Sf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},A8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Sf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},B8=function(a){return a.jb()?((0,g.G)()-a.D)/1E3:0},C8=function(a,b){a.F=b;
a.D=(0,g.G)()},D8=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},E8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&A8(a)},F8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.$b(a.l);b.hasPrevious=a.Sf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},H8=function(a,b){g.FF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.kC;this.o=this.l=null;this.H=(0,g.A)(this.sQ,this);this.D=(0,g.A)(this.jm,this);this.F=(0,g.A)(this.rQ,this);this.I=(0,g.A)(this.EQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.hw,this),NCa(this))):c=3;0!=c&&(b?this.hw(c):g.UD((0,g.A)(function(){this.hw(c)},this),0));
var d=LCa();d&&G8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},I8=function(a){return new z8(a.A.getPlayerContextData())},NCa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.PS,a),this))},a)},OCa=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},J8=function(a,b){50>a.B.Dc()&&g.mC(a.B,b)},L8=function(a,b,c){var d=I8(a);
C8(d,c);-1E3!=d.g&&(d.g=b);K8(a,d)},M8=function(a,b,c){a.A.sendMessage(b,c)},K8=function(a,b){OCa(a);
a.A.setPlayerContextData(F8(b));NCa(a)},G8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.jm(null));
a.o=b;a.o&&(R7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.jm(a.o.media[0]))},PCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=I8(a);b.contentId!=d.videoId&&R7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;C8(d,a.l.getEstimatedTime());K8(a,d)}else R7("CP","No cast media video. Ignoring state update.")},N8=function(a,b,c){return(0,g.A)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),M8(this,b,c))},a)},O8=function(a,b,c){g.FF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.J=this.K=window.NaN;this.R=[];this.A=this.D=this.o=this.Za=this.g=null;this.ra=a;this.R.push(g.oF(window,"beforeunload",(0,g.A)(this.xJ,this)));this.l=[];this.Za=new z8;this.Y=b.id;this.g=QCa(this,c);this.g.subscribe("handlerOpened",this.wQ,this);this.g.subscribe("handlerClosed",this.tQ,this);this.g.subscribe("handlerError",this.uQ,this);this.g.subscribe("handlerMessage",this.vQ,this);cCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.OG()&&g.LG("yt-remote-session-video-id",a)},this)},P8=function(a){R7("conn",a)},QCa=function(a,b){return new L7(O7(a.ra,"/bc"),b)},Q8=function(a,b){a.T("proxyStateChange",b)},RCa=function(a){a.B=g.UD((0,g.A)(function(){P8("Connecting timeout");
this.C(1)},a),2E4)},R8=function(a){g.WD(a.B);
a.B=window.NaN},S8=function(a){g.WD(a.K);
a.K=window.NaN},SCa=function(a){T8(a);
a.J=g.UD((0,g.A)(function(){U8(this,"getNowPlaying")},a),2E4)},T8=function(a){g.WD(a.J);
a.J=window.NaN},UCa=function(a,b){b&&(R8(a),S8(a));
b==(M7(a.g)&&(0,window.isNaN)(a.B))?b&&(Q8(a,1),U8(a,"getSubtitlesTrack")):b?(a.X()&&a.Za.reset(),Q8(a,1),U8(a,"getNowPlaying"),TCa(a)):a.C(1)},VCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Ub(b.params)?a.Za.l=null:a.Za.l=b.params,a.T("remotePlayerChange"))},WCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;E8(a.Za,c,d);a.T("remoteQueueChange")},YCa=function(a,b){b.params=b.params||{};
WCa(a,b);XCa(a,b);a.T("autoplayDismissed")},XCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
C8(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?SCa(a):T8(a);
a.T("remotePlayerChange")},ZCa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);C8(a.Za,(0,window.isNaN)(c)?0:c);a.T("remotePlayerChange")}},$Ca=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.T("remotePlayerChange")},aDa=function(a,b){a.D=b.params.videoId;
a.T("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},bDa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Sf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.T("previousNextChange")},TCa=function(a){g.WD(a.I);
a.I=g.UD((0,g.A)(a.C,a,1),864E5)},U8=function(a,b,c){c?P8("Sending: action="+b+", params="+g.wg(c)):P8("Sending: action="+b);
a.g.sendMessage(b,c)},V8=function(a){V7.call(this,"ScreenServiceProxy");
this.fd=a;this.l=[];this.l.push(this.fd.$_s("screenChange",(0,g.A)(this.oW,this)));this.l.push(this.fd.$_s("onlineScreenChange",(0,g.A)(this.rS,this)))},gDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.OD("MDX_CONFIG")||b;hBa();c7();W8||(W8=new N7(b?b.loungeApiHost:void 0),pBa()&&(W8.g="/api/loungedev"));X8||(X8=g.y("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",X8,void 0));cDa();var c=Y8();if(!c){var d=new d8(W8);g.va("yt.mdx.remote.screenService_",d,void 0);c=Y8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);HCa(a,d,function(a){a?Z8()&&y8(Z8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.VF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),$8("Initializing: "+g.wg(b)),a9.push(g.RF("yt-remote-cast2-availability-change",function(){g.VF("yt-remote-receiver-availability-change")})),a9.push(g.RF("yt-remote-cast2-receiver-selected",function(){b9(null);
g.VF("yt-remote-auto-connect","cast-selector-receiver")})),a9.push(g.RF("yt-remote-cast2-receiver-resumed",function(){g.VF("yt-remote-receiver-resumed","cast-selector-receiver")})),a9.push(g.RF("yt-remote-cast2-session-change",dDa)),a9.push(g.RF("yt-remote-connection-change",function(a){a?y8(Z8(),"YouTube TV"):c9()||(y8(null,null),KCa())})),a=d9(),b.isAuto&&(a.id+="#dial"),g.LF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),$8(" -- with channel params: "+
g.wg(a)),eDa(a),c.start(),Z8()||fDa())},iDa=function(){var a=hDa();
v8()&&g.MG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},hDa=function(){var a=Y8().fd.$_gos();
var b=e9();b&&f9()&&(Y6(a,b)||a.push(b));return gBa(a)},g9=function(){var a=jDa();
!a&&v8()&&JCa()&&(a={key:"cast-selector-receiver",name:JCa()});return a},jDa=function(){var a=hDa(),b=e9();
b||(b=c9());return g.Ja(a,function(a){return b&&U6(b,a.key)?!0:!1})},e9=function(){var a=Z8();
if(!a)return null;var b=Y8().ke();return Z6(b,a)},dDa=function(a){$8("remote.onCastSessionChange_: "+V6(a));
if(a){var b=e9();b&&b.id==a.id?y8(b.id,"YouTube TV"):(b&&h9(),i9(a,1))}else f9()&&h9()},h9=function(){w8()?t8().stopSession():r8("stopSession called before API ready.");
var a=f9();a&&(a.disconnect(1),j9(null))},k9=function(){var a=f9();
return!!a&&3!=a.getProxyState()},$8=function(a){R7("remote",a)},Y8=function(){if(!l9){var a=g.y("yt.mdx.remote.screenService_");
l9=a?new V8(a):null}return l9},Z8=function(){return g.y("yt.mdx.remote.currentScreenId_")},kDa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},lDa=function(){return g.y("yt.mdx.remote.connectData_")},b9=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},f9=function(){return g.y("yt.mdx.remote.connection_")},j9=function(a){var b=f9();
b9(null);a||kDa("");g.va("yt.mdx.remote.connection_",a,void 0);X8&&((0,g.C)(X8,function(b){b(a)}),X8.length=0);
b&&!a?g.VF("yt-remote-connection-change",!1):!b&&a&&g.VF("yt-remote-connection-change",!0)},c9=function(){var a=g.OG();
if(!a)return null;var b=Y8().ke();return Z6(b,a)},i9=function(a,b){e9()&&e9();
kDa(a.id);var c=new O8(W8,a,d9());c.connect(b,lDa());c.subscribe("beforeDisconnect",function(a){g.VF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){f9()&&j9(null)});
j9(c)},fDa=function(){var a=c9();
a?($8("Resume connection to: "+V6(a)),i9(a,0)):(d7(),KCa(),$8("Skipping connecting because no session screen found."))},cDa=function(){var a=d9();
if(g.Ub(a)){a=b7();var b=g.MG("yt-remote-session-name")||"",c=g.MG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},d9=function(){return g.y("yt.mdx.remote.channelParams_")||{}},eDa=function(a){a?(g.LG("yt-remote-session-app",a.app),g.LG("yt-remote-session-name",a.name)):(g.NG("yt-remote-session-app"),g.NG("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},m9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.CF(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.LR);this.o.O(b,"captionschanged",this.qQ);this.o.O(b,"captionssettingschanged",this.yE);this.o.O(b,"videoplayerreset",this.vp);this.o.O(b,"mdxautoplaycancel",this.CI);this.R=this.o.O(b,"onVolumeChange",this.GC);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.TC,this);c.subscribe("remotePlayerChange",this.pm,this);c.subscribe("remoteQueueChange",this.vp,this);c.subscribe("autoplayUpNext",this.rC,
this);c.subscribe("previousNextChange",this.QC,this);c.subscribe("nowAutoplaying",this.IC,this);c.subscribe("autoplayDismissed",this.qC,this);this.suggestion=null;this.H=new g.BP(64);this.A=new g.Vt(this.uE,500,this);g.N(this,this.A);this.B=new g.Vt(this.vE,1E3,this);g.N(this,this.B);this.J=new l7(this.SV,0,this);g.N(this,this.J);this.C={};this.K=new g.Vt(this.VE,1E3,this);g.N(this,this.K);this.I=new g.Uk(this.qO,1E3,this);g.N(this,this.I);this.N=g.z;this.yE();this.vp();this.pm()},n9=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.T("progresssync",b,d)},mDa=function(a){n9(a,0);
a.A.stop();o9(a,new g.BP(64))},q9=function(a,b){if(p9(a)&&!a.D){var c=null;
b&&(c={style:a.l.Hi()},g.bc(c,b));a.g.iE(a.l.getVideoData(1).videoId,c);a.C=I8(a.g).l}},r9=function(a,b){var c=a.l.cg();
if(c){var d=c.ie();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Tj;f=XAa(f);var n=I8(c);l=l||0;var q={videoId:k,currentIndex:l};E8(n,k,l);g.u(b)&&(C8(n,b),q.currentTime=b);g.u(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.wg(f));M8(c,"setPlaylist",q);e||K8(c,n);o9(a,new g.BP(1))},nDa=function(a,b){if(b){var c=a.l.yc("captions","tracklist",{Yz:1});
c&&c.length?(a.l.Md("captions","track",b),a.D=!1):(a.l.hk("captions"),a.D=!0)}else a.l.Md("captions","track",{})},p9=function(a){return I8(a.g).videoId==a.l.getVideoData(1).videoId},o9=function(a,b){a.B.stop();
var c=a.H;if(!g.GP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.fV(a.l,d);a.H=b;oDa(a.F,c,b)}},s9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",M:[{G:"div",L:"ytp-remote-display-status",M:[{G:"div",L:"ytp-remote-display-status-icon",M:[g.Soa()]},{G:"div",L:"ytp-remote-display-status-text",da:"{{statustext}}"}]}]});this.o=new g.VV(this,250);g.N(this,this.o);this.A=a;this.O(a,"presentingplayerstatechange",this.B);pDa(this,g.cV(a))},pDa=function(a,b){if(3==a.A.Ra()){var c={RECEIVER_NAME:a.A.yc("remote","currentReceiver").name};
c=g.X(b,128)?g.V("YTP_MDX_STATUS_ERROR_2",c):b.jb()||g.X(b,4)?g.V("YTP_MDX_STATUS_PLAYING_2",c):g.V("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},t9=function(a,b){g.b_.call(this,g.V("YTP_MDX_TITLE"),0,a,b);
this.o=a;this.H={};this.O(a,"onMdxReceiversChange",this.J);this.O(a,"presentingplayerstatechange",this.J);this.J()},u9=function(a){g.AV.call(this,a);
g.QG({YTP_MDX_CAST_SELECTOR:"Streamen\u2026",YTP_MDX_MY_COMPUTER:"Dieser Computer",YTP_MDX_PLAYER_ERROR:"Dieses Video ist nicht f\u00fcr die Remote-Wiedergabe verf\u00fcgbar.",YTP_MDX_STATUS_CONNECTED_2:"Verbunden mit $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Fehler auf $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Wiedergabe \u00fcber $RECEIVER_NAME",YTP_MDX_TITLE:"Wiedergeben auf"});this.o={key:X6(),name:g.V("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;
this.D=new g.BP(64);this.H=0;if(!g.VM(g.Y(this.g))){a=this.g;var b=g.CH(a);b&&(b=b.Ro())&&(b=new t9(a,b),g.N(this,b));b=new s9(a);g.N(this,b);g.uV(a,b.element,4)}},oDa=function(a,b,c){a.D=c;
a.g.T("presentingplayerstatechange",new g.LP(c,b))},v9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)h9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.cg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Zb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Tj,index:Math.max(a.g.YA(),0),currentTime:0==f?void 0:f};(d=XAa(d))&&(c.locationInfo=d);d=c}else d=null;$8("Connecting to: "+g.wg(b));"cast-selector-receiver"==b.key?(b9(d||null),w8()?t8().setLaunchParams(d||null):
r8("setLaunchParams called before ready.")):!d&&k9()&&Z8()==b.key?g.VF("yt-remote-connection-change",!0):(h9(),b9(d||null),d=Y8().ke(),(d=Z6(d,b.key))&&i9(d,1))}},EBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},v7={"'":"\\'"},qDa={},cBa={FX:"atp",d2:"ska",t1:"que",E0:"mus",Z1:"sus",NZ:"dsp"};
S6.prototype.Jn=function(){var a=new S6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var e7,a7="",i7=f7("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",wBa=f7("loadCastFramework")||f7("loadCastApplicationFramework"),GCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(l7,g.M);g.h=l7.prototype;g.h.sJ=function(a){this.A=arguments;this.g=!1;this.Ba?this.o=(0,g.G)()+this.rd:this.Ba=g.qg(this.B,this.rd)};
g.h.stop=function(){this.Ba&&(g.rg(this.Ba),this.Ba=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();l7.ba.V.call(this)};
g.h.tJ=function(){this.o?(this.Ba=g.qg(this.B,this.o-(0,g.G)()),this.o=null):(this.Ba=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};m7.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
m7.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=n7.prototype;g.h.mi=null;g.h.Df=!1;g.h.Ok=null;g.h.Zv=null;g.h.xk=null;g.h.Kj=null;g.h.jh=null;g.h.Hh=null;g.h.Oi=null;g.h.Sc=null;g.h.Km=0;g.h.Ef=null;g.h.rq=null;g.h.kh=null;g.h.zl=-1;g.h.PD=!0;g.h.Wh=!1;g.h.xs=0;g.h.Gp=null;var CBa={},q7={};g.h=n7.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.LU=function(a){a=a.target;var b=this.Gp;b&&3==g.fx(a)?b.Ij():this.dF(a)};
g.h.dF=function(a){try{if(a==this.Sc)a:{var b=g.fx(this.Sc),c=this.Sc.l,d=this.Sc.getStatus();if(g.vd&&!g.oc(10)||g.xd&&!g.nc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.bf&&!g.jx(this.Sc))break a;this.Wh||4!=b||7==c||(8==c||0>=d?this.g.xf(3):this.g.xf(2));x7(this);var e=this.Sc.getStatus();this.zl=e;var f=g.jx(this.Sc);(this.Df=200==e)?(4==b&&t7(this),this.B?(DBa(this,b,f),g.bf&&this.Df&&3==b&&(this.W.U(this.l,"tick",this.HU),this.l.start())):s7(this,f),this.Df&&!this.Wh&&(4==b?this.g.tp(this):
(this.Df=!1,p7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.kh=3,r7(13)):(this.kh=0,r7(14)),t7(this),u7(this))}}catch(k){this.Sc&&g.jx(this.Sc)}finally{}};
g.h.HU=function(){var a=g.fx(this.Sc),b=g.jx(this.Sc);this.Km<b.length&&(x7(this),DBa(this,a,b),this.Df&&4!=a&&p7(this))};
g.h.ST=function(a){w7((0,g.A)(this.RT,this,a),0)};
g.h.RT=function(a){this.Wh||(x7(this),s7(this,a),p7(this))};
g.h.bD=function(a){w7((0,g.A)(this.QT,this,a),0)};
g.h.QT=function(a){this.Wh||(t7(this),this.Df=a,this.g.tp(this),this.g.xf(4))};
g.h.cancel=function(){this.Wh=!0;t7(this)};
g.h.kU=function(){this.Ok=null;var a=(0,g.G)();0<=a-this.Zv?(2!=this.Kj&&this.g.xf(3),t7(this),this.kh=2,r7(18),u7(this)):GBa(this,this.Zv-a)};g.h=JBa.prototype;g.h.us=null;g.h.se=null;g.h.Hp=!1;g.h.oz=null;g.h.Wn=null;g.h.Dt=null;g.h.ws=null;g.h.Ne=null;g.h.Cg=-1;g.h.yl=null;g.h.Vk=null;g.h.connect=function(a){this.ws=a;a=z7(this.g,null,this.ws);r7(3);this.oz=(0,g.G)();var b=this.g.F;null!=b?(this.yl=b[0],(this.Vk=b[1])?(this.Ne=1,KBa(this)):(this.Ne=2,B7(this))):(R6(a,"MODE","init"),this.se=new n7(this,void 0,void 0,void 0),this.se.mi=this.us,o7(this.se,a,!1,null,!0),this.Ne=0)};
g.h.DI=function(a){if(a)this.Ne=2,B7(this);else{r7(4);var b=this.g;b.Pf=b.ah.Cg;I7(b,9)}a&&this.xf(2)};
g.h.Kr=function(a){return this.g.Kr(a)};
g.h.abort=function(){this.se&&(this.se.cancel(),this.se=null);this.Cg=-1};
g.h.nz=function(){return!1};
g.h.UC=function(a,b){this.Cg=a.zl;if(0==this.Ne)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Pf=this.Cg;I7(c,2);return}this.yl=c[0];this.Vk=c[1]}else c=this.g,c.Pf=this.Cg,I7(c,2);else if(2==this.Ne)if(this.Hp)r7(7),this.Dt=(0,g.G)();else if("11111"==b){if(r7(6),this.Hp=!0,this.Wn=(0,g.G)(),c=this.Wn-this.oz,!g.vd||g.oc(10)||500>c)this.Cg=200,this.se.cancel(),r7(12),A7(this.g,this,!0)}else r7(8),this.Wn=this.Dt=(0,g.G)(),this.Hp=!1};
g.h.tp=function(){this.Cg=this.se.zl;if(this.se.Df)0==this.Ne?this.Vk?(this.Ne=1,KBa(this)):(this.Ne=2,B7(this)):2==this.Ne&&((!g.vd||g.oc(10)?!this.Hp:200>this.Dt-this.Wn)?(r7(11),A7(this.g,this,!1)):(r7(12),A7(this.g,this,!0)));else{0==this.Ne?r7(9):2==this.Ne&&r7(10);var a=this.g;a.Pf=this.Cg;I7(a,2)}};
g.h.Bm=function(){return this.g.Bm()};
g.h.isActive=function(){return this.g.isActive()};
g.h.xf=function(a){this.g.xf(a)};g.h=C7.prototype;g.h.kl=null;g.h.Xd=null;g.h.xc=null;g.h.ts=null;g.h.ao=null;g.h.Fx=null;g.h.po=null;g.h.gm=0;g.h.IP=0;g.h.qd=null;g.h.eh=null;g.h.rg=null;g.h.bi=null;g.h.ah=null;g.h.qq=null;g.h.Yj=-1;g.h.mA=-1;g.h.Pf=-1;g.h.vj=0;g.h.hj=0;g.h.Yh=8;var J7=new g.Bf;g.B(MBa,g.$e);g.B(NBa,g.$e);g.B(OBa,g.$e);g.h=C7.prototype;g.h.connect=function(a,b,c,d,e){r7(0);this.ts=b;this.kl=c||{};d&&g.u(e)&&(this.kl.OSID=d,this.kl.OAID=e);this.C?(w7((0,g.A)(this.ay,this,a),100),SBa(this)):this.ay(a)};
g.h.ay=function(a){this.ah=new JBa(this);this.ah.us=null;this.ah.l=this.B;this.ah.connect(a)};
g.h.nz=function(){return 0==this.g};
g.h.ZC=function(a){this.eh=null;VBa(this,a)};
g.h.YC=function(){this.rg=null;this.xc=new n7(this,this.o,"rpc",this.D);this.xc.mi=null;this.xc.xs=0;var a=this.Fx.clone();g.Cm(a,"RID","rpc");g.Cm(a,"SID",this.o);g.Cm(a,"CI",this.qq?"0":"1");g.Cm(a,"AID",this.Yj);D7(this,a);if(!g.vd||g.oc(10))g.Cm(a,"TYPE","xmlhttp"),o7(this.xc,a,!0,this.po,!1);else{g.Cm(a,"TYPE","html");var b=this.xc,c=!!this.po;b.Kj=3;b.jh=Q6(a.clone());FBa(b,c)}};
g.h.UC=function(a,b){if(0!=this.g&&(this.xc==a||this.Xd==a))if(this.Pf=a.zl,this.Xd==a&&3==this.g)if(7<this.Yh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.rg){if(this.xc)if(this.xc.xk+3E3<this.Xd.xk)F7(this),this.xc.cancel(),this.xc=null;else break a;H7(this);r7(19)}}else this.mA=c[1],0<this.mA-this.Yj&&37500>c[2]&&this.qq&&0==this.hj&&!this.bi&&(this.bi=w7((0,g.A)(this.lQ,this),6E3));else I7(this,11)}else b!=qDa.IY.g&&I7(this,11);else if(this.xc==a&&
F7(this),!g.D(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.Yj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.po=e[2],e=e[3],null!=e?this.Yh=e:this.Yh=6,this.g=3,this.qd&&this.qd.Rx(),this.Fx=z7(this,this.Bm()?this.po:null,this.ts),WBa(this)):"stop"==e[0]&&I7(this,7):3==this.g&&("stop"==e[0]?I7(this,7):"noop"!=e[0]&&this.qd&&this.qd.Qx(e),this.hj=0)}}};
g.h.lQ=function(){null!=this.bi&&(this.bi=null,this.xc.cancel(),this.xc=null,H7(this),r7(20))};
g.h.tp=function(a){if(this.xc==a){F7(this);this.xc=null;var b=2}else if(this.Xd==a)this.Xd=null,b=1;else return;this.Pf=a.zl;if(0!=this.g)if(a.Df)1==b?(b=(0,g.G)()-a.xk,J7.dispatchEvent(new NBa(J7,a.Oi?a.Oi.length:0,b,this.vj)),E7(this),this.A.length=0):WBa(this);else{var c=a.kh,d;if(!(d=3==c||7==c||0==c&&0<this.Pf)){if(d=1==b)this.Xd||this.eh||1==this.g||2<=this.vj?d=!1:(this.eh=w7((0,g.A)(this.ZC,this,a),XBa(this,this.vj)),this.vj++,d=!0);d=!(d||2==b&&H7(this))}if(d)switch(c){case 1:I7(this,5);
break;case 4:I7(this,10);break;case 3:I7(this,6);break;case 7:I7(this,12);break;default:I7(this,2)}}};
g.h.bJ=function(a){if(!g.Na(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.EV=function(a){a?r7(2):(r7(1),YBa(this,8))};
g.h.Kr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.$w;a.F=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.xf=function(a){J7.dispatchEvent(new OBa(J7,a))};
g.h.Bm=function(){return!(!g.vd||g.oc(10))};
g.h=ZBa.prototype;g.h.Rx=function(){};
g.h.Qx=function(){};
g.h.Px=function(){};
g.h.xr=function(){};
g.h.Uy=function(){return{}};
g.h.isActive=function(){return!0};g.B(K7,g.M);g.h=K7.prototype;g.h.IT=function(){this.rd=Math.min(3E5,2*this.rd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.rd+15E3*Math.random();g.Wt(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.rd=5E3};g.B(L7,ZBa);g.h=L7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Qd=function(a){return this.o.Qd(a)};
g.h.T=function(a,b){return this.o.T.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Ye(this.o),bCa(this),g.Ye(this.l),this.l=null)};
g.h.ka=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new C7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Yj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.bc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):M7(this)&&TBa(this.g,c)};
g.h.Rx=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)TBa(this.g,a[b])}this.T("handlerOpened")};
g.h.Px=function(a){var b=2==a&&401==this.g.Pf;4==a||b||this.l.start();this.T("handlerError",a)};
g.h.xr=function(a){if(!this.l.isActive())this.T("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Uy=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.bc(a,this.B);return a};
g.h.Qx=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),RBa(this.g)):this.T("handlerMessage",new $Ba(a[0],a[1]))};
g.h.kW=function(){this.l.isActive();var a=this.g,b=0;a.xc&&b++;a.Xd&&b++;0!=b||this.connect(this.B,this.A)};N7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
N7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
N7.prototype.B=function(a){a(Error("request timed out"))};var jCa=(0,g.G)(),Q7=null,T7=Array(50),S7=-1,U7=!1;g.B(V7,g.FF);V7.prototype.ke=function(){return this.g};
V7.prototype.contains=function(a){return!!Y6(this.g,a)};
V7.prototype.get=function(a){return a?Z6(this.g,a):null};
V7.prototype.info=function(a){R7(this.D,a)};g.B(W7,g.FF);var rDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=W7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ba)&&this.iF()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ba)||(g.WD(this.Ba),this.Ba=window.NaN)};
g.h.V=function(){this.stop();W7.ba.V.call(this)};
g.h.iF=function(){this.Ba=window.NaN;this.g=g.kE(O7(this.C,"/pairing/get_screen"),{method:"POST",Nb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.A)(this.mW,this),onError:(0,g.A)(this.lW,this),yd:(0,g.A)(this.nW,this)})};
g.h.mW=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.T("pairingComplete",new T6(c))};
g.h.lW=function(a){this.g=null;a.status&&404==a.status?this.l>=rDa.length?this.T("pairingFailed",Error("DIAL polling timed out")):(a=rDa[this.l],this.Ba=g.UD((0,g.A)(this.iF,this),a),this.l++):this.T("pairingFailed",Error("Server error "+a.status))};
g.h.nW=function(){this.g=null;this.T("pairingFailed",Error("Server not responding"))};g.B(Y7,V7);g.h=Y7.prototype;g.h.start=function(){X7(this)&&this.T("screenChange");!g.MG("yt-remote-lounge-token-expiration")&&nCa(this);g.WD(this.l);this.l=g.UD((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){X7(this);kCa(this,a);Z7(this,!1);this.T("screenChange");b(a);a.token||nCa(this)};
g.h.remove=function(a,b){var c=X7(this);mCa(this,a)&&(Z7(this,!1),c=!0);b(a);c&&this.T("screenChange")};
g.h.lq=function(a,b,c,d){var e=X7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,Z7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.T("screenChange")};
g.h.V=function(){g.WD(this.l);Y7.ba.V.call(this)};
g.h.GJ=function(a){X7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}Z7(this,!b);b&&R7(this.D,"Missed "+b+" lounge tokens.")};
g.h.FJ=function(a){R7(this.D,"Requesting lounge tokens failed: "+a)};g.B(a8,g.FF);g.h=a8.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.MG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?c8(this):(this.A=(0,g.G)()+3E5,g.LG("yt-remote-fast-check-period",this.A),this.ov())};
g.h.isEmpty=function(){return g.Ub(this.g)};
g.h.update=function(){$7("Updating availability on schedule.");var a=this.C(),b=g.Ib(this.g,function(b,d){return b&&!!Z6(a,d)},this);
b8(this,b)};
g.h.V=function(){g.WD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);a8.ba.V.call(this)};
g.h.ov=function(){g.WD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=qCa(this);if(g.Lb(a)){var b=O7(this.B,"/pairing/get_screen_availability");this.l=P7(this.B,b,{lounge_token:g.Ob(a).join(",")},(0,g.A)(this.pT,this,a),(0,g.A)(this.oT,this))}else b8(this,{}),c8(this)};
g.h.pT=function(a,b){this.l=null;var c=g.Ob(qCa(this));if(g.fb(c,g.Ob(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;b8(this,d);c8(this)}else this.hc("Changing Screen set during request."),this.ov()};
g.h.oT=function(a){this.hc("Screen availability failed: "+a);this.l=null;c8(this)};
g.h.hc=function(a){R7("OnlineScreenService",a)};g.B(d8,V7);g.h=d8.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.T("screenChange"),this.l.isEmpty()||this.T("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.lq=function(a,b,c,d){this.o.contains(a)?this.o.lq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,R7(this.D,a),d(Error(a)))};
g.h.ke=function(a){return a?this.g:g.Ua(this.g,(0,g.Id)(this.A,function(a){return!this.contains(a)},this))};
g.h.jF=function(){return(0,g.Id)(this.ke(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.kF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new W7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Ye(f);d(e8(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ye(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.pW=function(a,b,c,d){g.kE(O7(this.C,"/pairing/get_screen"),{method:"POST",Nb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new T6(d.screen||{});if(!e.name||uCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);uCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(e8(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
yd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Ye(this.o);g.Ye(this.l);d8.ba.V.call(this)};
g.h.VJ=function(){vCa(this);this.T("screenChange");this.l.update()};
d8.prototype.dispose=d8.prototype.dispose;g.B(g8,g.FF);g.h=g8.prototype;g.h.up=function(a){this.o=a;this.T("sessionScreen",this.o)};
g.h.re=function(a){this.ka()||(a&&h8(this,""+a),this.o=null,this.T("sessionScreen",null))};
g.h.info=function(a){R7(this.K,a)};
g.h.mF=function(){return null};
g.h.xv=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){h8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.xv("");g8.ba.V.call(this)};g.B(i8,g8);g.h=i8.prototype;g.h.vv=function(a){if(this.g){if(this.g==a)return;h8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);xCa(this)};
g.h.ak=function(a){this.info("launchWithParams no-op for Cast: "+g.wg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.re()},this),(0,g.A)(function(){this.re(Error("Failed to stop receiver app."))},this)):this.re(Error("Stopping cast device witout session."))};
g.h.xv=g.z;g.h.V=function(){this.info("disposeInternal");g.WD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;i8.ba.V.call(this)};
g.h.wU=function(a,b){if(!this.ka())if(b){var c=g.Uw(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.wg(c));switch(d){case "mdxSessionStatus":wCa(this,c.screenId);break;default:h8(this,"Unknown youtube message: "+d)}}else h8(this,"Unable to parse message.")}else h8(this,"No data in message.")};
g.h.fz=function(a,b,c,d){tCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(h8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.UD((0,g.A)(this.fz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.mF=function(){return this.g};
g.h.qW=function(a){this.ka()||a||(h8(this,"Cast session died."),this.re())};g.B(j8,g8);g.h=j8.prototype;g.h.vv=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.ak=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.z;g.WD(this.C);this.A?this.A.stop((0,g.A)(this.re,this,null),(0,g.A)(this.re,this,"Failed to stop DIAL device.")):this.re()};
g.h.V=function(){this.g();this.g=g.z;g.WD(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;j8.ba.V.call(this)};
g.h.tW=function(a){this.ka()||a||(h8(this,"DIAL session died."),this.g(),this.g=g.z,this.re())};
g.h.ht=function(a){this.I=X6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,zCa(this));a(b);yCa(this)}else this.D=(0,g.A)(function(){g.WD(this.C);this.D=g.z;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,zCa(this));a(b);yCa(this)},this),this.C=g.UD((0,g.A)(function(){this.D()},this),100)};
g.h.jL=function(a,b,c){tCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.up(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.ht(b,c)},this),(0,g.A)(function(a){h8(this,"Failed to get DIAL screen: "+a);
this.ht(b,c)},this))};g.B(k8,g8);k8.prototype.stop=function(){this.re()};
k8.prototype.vv=g.z;k8.prototype.ak=function(){g.WD(this.g);this.g=window.NaN;var a=Z6(this.H.ke(),this.l.label);a?this.up(a):this.re(Error("No such screen"))};
k8.prototype.V=function(){g.WD(this.g);this.g=window.NaN;k8.ba.V.call(this)};g.B(l8,g.FF);g.h=l8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.VC,this),(0,g.A)(this.ZS,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.VQ,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.A),gCa(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.lF,this)),this.o=BCa(this),window.chrome.cast.setCustomReceivers(this.o,g.z,(0,g.A)(function(a){this.hc("Failed to set initial custom receivers: "+g.wg(a))},this)),this.T("yt-remote-cast2-availability-change",n8(this)),b(!0))},this),(0,g.A)(function(a){this.hc("Failed to initialize API: "+g.wg(a));
b(!1)},this))};
g.h.nV=function(a,b){m8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)m8("Unsetting old screen status: "+this.g.l.friendlyName),o8(this,null)}if(a&&b){if(!this.g){c=Z6(this.l.ke(),a);if(!c){m8("setConnectedScreenStatus: Unknown screen.");return}var d=ACa(this,c);d||(m8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.z,(0,g.A)(function(a){this.hc("Failed to set initial custom receivers: "+g.wg(a))},this)));
m8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);o8(this,new k8(this.l,d),!0)}this.g.xv(b)}else m8("setConnectedScreenStatus: no screen.")};
g.h.oV=function(a){this.ka()?this.hc("Setting connection data on disposed cast v2"):this.g?this.g.ak(a):this.hc("Setting connection data without a session")};
g.h.sW=function(){this.ka()?this.hc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),o8(this,null)):m8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.VC,this),(0,g.A)(this.uT,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.lF,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Sa(g.y("yt.mdx.remote.debug.handlers_")||[],dCa);g.Ye(this.g);l8.ba.V.call(this)};
g.h.hc=function(a){R7("Controller",a)};
g.h.WC=function(a,b){this.g==a&&(b||o8(this,null),this.T("yt-remote-cast2-session-change",b))};
g.h.VS=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),m8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)m8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{m8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.T("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:o8(this,
new k8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:o8(this,new j8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:o8(this,new i8(this.l,a));break;default:this.hc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.hc("Stopping receiver w/o session: "+a.friendlyName)}else this.hc("onReceiverAction_ called without receiver.")};
g.h.VQ=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.hc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.hc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return m8("Reselecting dial screen."),
this.T("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.hc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);o8(this,new j8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.jL,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.ht,b))};
g.h.VC=function(a){if(!this.ka()){m8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)m8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),o8(this,new i8(this.l,b),!0);else{this.hc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=Z6(this.l.ke(),c.label);
d&&U6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(m8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ye(this.g),this.g=new i8(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.WC,this,this.g)),this.g.ak(null));this.g.vv(a)}}};
g.h.rW=function(){return this.g?this.g.mF():null};
g.h.uT=function(a){this.ka()||(this.hc("Failed to estabilish a session: "+g.wg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&o8(this,null))};
g.h.ZS=function(a){m8("Receiver availability updated: "+a);if(!this.ka()){var b=n8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;n8(this)!=b&&this.T("yt-remote-cast2-availability-change",n8(this))}};
g.h.lF=function(){this.ka()||(this.o=BCa(this),m8("Updating custom receivers: "+g.wg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.z,(0,g.A)(function(){this.hc("Failed to set custom receivers.")},this)),this.T("yt-remote-cast2-availability-change",n8(this)))};
l8.prototype.setLaunchParams=l8.prototype.oV;l8.prototype.setConnectedScreenStatus=l8.prototype.nV;l8.prototype.stopSession=l8.prototype.sW;l8.prototype.getCastSession=l8.prototype.rW;l8.prototype.requestSession=l8.prototype.requestSession;l8.prototype.init=l8.prototype.init;l8.prototype.dispose=l8.prototype.dispose;var u8=[];g.h=z8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";A8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Sf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.jb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+B8(this):this.H};
g.h.clone=function(){return new z8(F8(this))};g.B(H8,g.FF);g.h=H8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.z,N8(this,"play")):M8(this,"play"),L8(this,1,D8(I8(this))),this.T("remotePlayerChange")):J8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.z,N8(this,"pause")):M8(this,"pause"),L8(this,2,D8(I8(this))),this.T("remotePlayerChange")):J8(this,this.pause)};
g.h.hF=function(a){if(1==this.g){if(this.l){var b=I8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.z,N8(this,"seekTo",{newTime:a}))}else M8(this,"seekTo",{newTime:a});L8(this,3,a);this.T("remotePlayerChange")}else J8(this,g.Ea(this.hF,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.z,N8(this,"stopVideo")):M8(this,"stopVideo");var a=I8(this);a.index=-1;a.videoId="";A8(a);K8(this,a);this.T("remotePlayerChange")}else J8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=I8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){R7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){R7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);M8(this,"setVolume",e)}c.muted=b;c.volume=a;K8(this,c)}else J8(this,g.Ea(this.setVolume,a,b))};
g.h.iE=function(a,b){if(1==this.g){var c=I8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.wg(b.style),g.bc(d,c.l));M8(this,"setSubtitlesTrack",d);K8(this,c)}else J8(this,g.Ea(this.iE,a,b))};
g.h.gw=function(a,b){if(1==this.g){M8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Hb.id});var c=I8(this);c.audioTrackId=b.Hb.id;K8(this,c)}else J8(this,g.Ea(this.gw,a,b))};
g.h.gF=function(a,b){if(1==this.g){if(a&&b){var c=I8(this);E8(c,a,b);K8(this,c)}M8(this,"previous")}else J8(this,g.Ea(this.gF,a,b))};
g.h.fF=function(a,b){if(1==this.g){if(a&&b){var c=I8(this);E8(c,a,b);K8(this,c)}M8(this,"next")}else J8(this,g.Ea(this.fF,a,b))};
g.h.wy=function(){1==this.g?M8(this,"dismissAutoplay"):J8(this,this.wy)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.T("proxyStateChange",a,this.g)}H8.ba.dispose.call(this)};
g.h.V=function(){OCa(this);this.A=null;this.B.clear();G8(this,null);H8.ba.V.call(this)};
g.h.hw=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.T("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.nC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.PS=function(a,b){this.T(a,b)};
g.h.sQ=function(a){if(!a)this.jm(null),G8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=I8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)R7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,K8(this,b)}};
g.h.jm=function(a){R7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),PCa(this),this.T("remotePlayerChange")};
g.h.rQ=function(a){a?(PCa(this),this.T("remotePlayerChange")):this.jm(null)};
g.h.EQ=function(){var a=LCa();a&&G8(this,a)};
g.h.hc=function(a){R7("CP",a)};g.B(O8,g.FF);g.h=O8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;C8(this.Za,m);this.A="UNSUPPORTED";P8("Connecting with setPlaylist and params: "+g.wg(l));this.g.connect({method:"setPlaylist",
params:g.wg(l)},a,kBa())}else P8("Connecting without params"),this.g.connect({},a,kBa());RCa(this)};
g.h.dispose=function(){this.ka()||(this.T("beforeDispose"),Q8(this,3));O8.ba.dispose.call(this)};
g.h.V=function(){R8(this);T8(this);S8(this);g.WD(this.H);this.H=window.NaN;g.WD(this.I);this.I=window.NaN;this.o=null;g.pF(this.R);this.R.length=0;this.g.dispose();O8.ba.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.xJ=function(){this.C(2)};
g.h.wQ=function(){P8("Channel opened");this.N&&(this.N=!1,S8(this),this.K=g.UD((0,g.A)(function(){P8("Timing out waiting for a screen.");this.C(1)},this),15E3));
oBa(aCa(this.g),this.Y)};
g.h.tQ=function(){P8("Channel closed");(0,window.isNaN)(this.B)?d7(!0):d7();this.dispose()};
g.h.uQ=function(a){d7();(0,window.isNaN)(this.F())?(P8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,P8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),Q8(this,2))};
g.h.vQ=function(a){a.params?P8("Received: action="+a.action+", params="+g.wg(a.params)):P8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Uw(a.params.devices);this.l=(0,g.I)(a,function(a){return new S6(a)});
a=!!g.Ja(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
UCa(this,a);break;case "loungeScreenDisconnected":g.Ta(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
UCa(this,!1);break;case "remoteConnected":var b=new S6(g.Uw(a.params.device));g.Ja(this.l,function(a){return b?a.id==b.id:!1})||g.Qa(this.l,b);
break;case "remoteDisconnected":b=new S6(g.Uw(a.params.device));g.Ta(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":WCa(this,a);break;case "nowPlaying":YCa(this,a);break;case "onStateChange":XCa(this,a);break;case "onAdStateChange":ZCa(this,a);break;case "onVolumeChanged":$Ca(this,a);break;case "onSubtitlesTrackChanged":VCa(this,a);break;case "nowAutoplaying":aDa(this,a);break;case "autoplayDismissed":this.T("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.T("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.T("autoplayModeChange",this.A);"DISABLED"==this.A&&this.T("autoplayDismissed");break;case "onHasPreviousNextChanged":bDa(this,a);break;case "requestAssistedSignIn":this.T("assistedSignInRequested",a.params.authCode);break;default:P8("Unrecognized action: "+a.action)}};
g.h.XU=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&U8(this,"getNowPlaying")}};
O8.prototype.subscribe=O8.prototype.subscribe;O8.prototype.unsubscribeByKey=O8.prototype.Qd;O8.prototype.ga=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.F())?M7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
O8.prototype.getProxyState=O8.prototype.ga;O8.prototype.C=function(a){P8("Disconnecting with "+a);R8(this);this.T("beforeDisconnect",a);1==a&&d7();bCa(this.g,a);this.dispose()};
O8.prototype.disconnect=O8.prototype.C;O8.prototype.fa=function(){var a=this.Za;this.o&&(a=this.Za.clone(),E8(a,this.o,a.index));return F8(a)};
O8.prototype.getPlayerContextData=O8.prototype.fa;
O8.prototype.na=function(a){var b=new z8(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.WD(this.H),this.H=g.UD((0,g.A)(this.XU,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&D8(this.Za)==D8(b)&&g.wg(this.Za.l)==g.wg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.C)(c,function(a){this.T(a)},this)};
O8.prototype.setPlayerContextData=O8.prototype.na;O8.prototype.X=function(){var a=this.g.C.id,b=g.Ja(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
O8.prototype.getOtherConnectedRemoteId=O8.prototype.X;O8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
O8.prototype.getReconnectTimeout=O8.prototype.F;O8.prototype.Z=function(){return this.A||"UNSUPPORTED"};
O8.prototype.getAutoplayMode=O8.prototype.Z;O8.prototype.aa=function(){return this.D||""};
O8.prototype.getAutoplayVideoId=O8.prototype.aa;O8.prototype.sa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Xt(a.g);a.start()}};
O8.prototype.reconnect=O8.prototype.sa;O8.prototype.ia=function(a,b){U8(this,a,b);TCa(this)};
O8.prototype.sendMessage=O8.prototype.ia;g.B(V8,V7);g.h=V8.prototype;g.h.ke=function(a){return this.fd.$_gs(a)};
g.h.contains=function(a){return!!this.fd.$_c(a)};
g.h.get=function(a){return this.fd.$_g(a)};
g.h.start=function(){this.fd.$_st()};
g.h.add=function(a,b,c){this.fd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.fd.$_r(a,b,c)};
g.h.lq=function(a,b,c,d){this.fd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.fd.$_ubk(this.l[a]);this.l.length=0;this.fd=null;V8.ba.V.call(this)};
g.h.oW=function(){this.T("screenChange")};
g.h.rS=function(){this.T("onlineScreenChange")};
d8.prototype.$_st=d8.prototype.start;d8.prototype.$_gspc=d8.prototype.pW;d8.prototype.$_gsppc=d8.prototype.kF;d8.prototype.$_c=d8.prototype.contains;d8.prototype.$_g=d8.prototype.get;d8.prototype.$_a=d8.prototype.add;d8.prototype.$_un=d8.prototype.lq;d8.prototype.$_r=d8.prototype.remove;d8.prototype.$_gs=d8.prototype.ke;d8.prototype.$_gos=d8.prototype.jF;d8.prototype.$_s=d8.prototype.subscribe;d8.prototype.$_ubk=d8.prototype.Qd;var W8=null,X8=null,l9=null,a9=[];g.t(m9,g.M);g.h=m9.prototype;
g.h.V=function(){g.M.prototype.V.call(this);this.A.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.TC,this);this.g.unsubscribe("remotePlayerChange",this.pm,this);this.g.unsubscribe("remoteQueueChange",this.vp,this);this.g.unsubscribe("autoplayUpNext",this.rC,this);this.g.unsubscribe("previousNextChange",this.QC,this);this.g.unsubscribe("nowAutoplaying",this.IC,this);this.g.unsubscribe("autoplayDismissed",this.qC,this);this.g=this.F=null};
g.h.sB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(p9(this)){if(!I8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":I8(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Ij(c[0],c[1]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.gw(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();r9(this,0==c?void 0:c);break;case "control_seek":r9(this,c[0]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.gw(this.l.getVideoData(1).videoId,c)}};
g.h.qQ=function(a){this.J.sJ(a)};
g.h.SV=function(a){this.sB("control_subtitles_set_track",g.Ub(a)?null:a)};
g.h.yE=function(){var a=this.l.yc("captions","track");g.Ub(a)||q9(this,a)};
g.h.GC=function(a){if(p9(this)){this.g.unsubscribe("remotePlayerChange",this.pm,this);var b=Math.round(a.volume);a=!!a.muted;var c=I8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.pm,this)}};
g.h.LR=function(){g.Ub(this.C)||nDa(this,this.C);this.D=!1};
g.h.TC=function(a,b){this.B.stop();2==b&&this.vE()};
g.h.pm=function(){if(p9(this)){this.A.stop();var a=I8(this.g);switch(a.g){case 1081:case 1:o9(this,new g.BP(8));this.uE();break;case 1085:case 3:o9(this,new g.BP(9));break;case 1083:case 0:o9(this,new g.BP(2));this.I.stop();n9(this,this.l.getVideoData().lengthSeconds);break;case 1084:o9(this,new g.BP(4));break;case 2:o9(this,new g.BP(4));n9(this,D8(a));break;case -1:o9(this,new g.BP(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.V("YTP_MDX_PLAYER_ERROR")},o9(this,new g.BP(128,a))}a=
I8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,nDa(this,a));a=I8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.K.isActive()||this.VE()}else mDa(this)};
g.h.QC=function(){this.l.T("mdxpreviousnextchange")};
g.h.vp=function(){p9(this)||mDa(this)};
g.h.CI=function(){this.g.wy()};
g.h.rC=function(a){a&&(a=g.kE("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.VT,this)}))&&(this.N=(0,g.A)(a.abort,a))};
g.h.VT=function(a,b){var c=new g.tO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.T("mdxautoplayupnext",c)};
g.h.IC=function(a){(0,window.isNaN)(a)||this.l.T("mdxnowautoplaying",a)};
g.h.qC=function(){this.l.T("mdxautoplaycanceled")};
g.h.qO=function(a,b){-1==I8(this.g).g?r9(this,a):b&&this.g.hF(a)};
g.h.VE=function(){if(p9(this)){var a=I8(this.g);this.o.Da(this.R);a.muted?this.l.mute():this.l.dg();this.l.setVolume(a.volume);this.R=this.o.O(this.l,"onVolumeChange",this.GC)}};
g.h.uE=function(){this.A.stop();if(!this.g.ka()){var a=I8(this.g);a.jb()&&o9(this,new g.BP(8));n9(this,D8(a));this.A.start()}};
g.h.vE=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.t(s9,g.W);s9.prototype.B=function(a){pDa(this,a.state)};g.t(t9,g.b_);t9.prototype.J=function(){var a=this.o.yc("remote","receivers");a&&1<a.length&&!this.o.yc("remote","quickCast")?(this.H=g.ib(a,this.C,this),g.c_(this,(0,g.I)(a,this.C)),a=this.o.yc("remote","currentReceiver"),this.wf(this.C(a)),this.enable(!0)):this.enable(!1)};
t9.prototype.C=function(a){return a.key};
t9.prototype.vf=function(a){return"cast-selector-receiver"==a?g.V("YTP_MDX_CAST_SELECTOR"):this.H[a].name};
t9.prototype.wd=function(a){g.b_.prototype.wd.call(this,a);this.o.Md("remote","currentReceiver",this.H[a]);this.B.Rb()};g.t(u9,g.AV);g.h=u9.prototype;g.h.create=function(){gDa(g.IM(g.Y(this.g)));this.C.push(g.RF("yt-remote-before-disconnect",this.mQ,this));this.C.push(g.RF("yt-remote-connection-change",this.aT,this));this.C.push(g.RF("yt-remote-receiver-availability-change",this.RC,this));this.C.push(g.RF("yt-remote-auto-connect",this.YS,this));this.C.push(g.RF("yt-remote-receiver-resumed",this.XS,this));this.RC()};
g.h.load=function(){this.g.iu();g.AV.prototype.load.call(this);this.B=new m9(this,this.g,this.l);var a=(a=lDa())?a.currentTime:0;var b=k9()?new H8(f9(),void 0):null;0==a&&b&&(a=D8(I8(b)));0!=a&&(this.H=a||0,this.g.T("progresssync",a,void 0));oDa(this,this.D,this.D);g.x0(this.g.app,6)};
g.h.unload=function(){this.g.T("mdxautoplaycanceled");this.A=this.o;g.Ze(this.B,this.l);this.l=this.B=null;g.AV.prototype.unload.call(this);g.x0(this.g.app,5)};
g.h.V=function(){g.SF(this.C);g.AV.prototype.V.call(this)};
g.h.Yl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.sB.apply(this.B,[a].concat(g.oa(c)))};
g.h.oJ=function(){return this.loaded?this.B.suggestion:null};
g.h.Sf=function(){return this.l?I8(this.l).Sf:!1};
g.h.hasNext=function(){return this.l?I8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.eO=function(){var a=I8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.gd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+B8(a):a.A,isPeggedToLive:1>=(a.C?a.o+B8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+B8(a):a.o,seekableStart:0<a.B?a.B+B8(a):a.B}};
g.h.fO=function(){this.l&&this.l.fF()};
g.h.gO=function(){this.l&&this.l.gF()};
g.h.mQ=function(a){1==a&&(this.I=this.l?I8(this.l):null)};
g.h.aT=function(){var a=k9()?new H8(f9(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ye(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.WA(a.videoId,D8(a)));this.g.T("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.RC=function(){this.F=[this.o].concat(iDa());var a=g9()||this.o;v9(this,a);this.g.va("onMdxReceiversChange")};
g.h.YS=function(){var a=g9();v9(this,a)};
g.h.XS=function(){this.A=g9()};
g.h.dO=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?x8():v9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&x8(),!0):!1}};
g.h.hO=function(){M8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Pc=function(){return!1};g.rY.remote=u9;})(_yt_player);
